import type { Project, Material, Testimonial, BlogPost, FAQItem, ProcessStep } from '@/types';

export const projectImages = {
  kitchen1: 'https://images.pexels.com/photos/8143944/pexels-photo-8143944.jpeg?auto=compress&cs=tinysrgb&w=1200',
  kitchen2: 'https://images.pexels.com/photos/36777559/pexels-photo-36777559.jpeg?auto=compress&cs=tinysrgb&w=1200',
  kitchen3: 'https://images.pexels.com/photos/5008398/pexels-photo-5008398.jpeg?auto=compress&cs=tinysrgb&w=1200',
  kitchen4: 'https://images.pexels.com/photos/19878513/pexels-photo-19878513.jpeg?auto=compress&cs=tinysrgb&w=1200',
  kitchen5: 'https://images.pexels.com/photos/15668081/pexels-photo-15668081.jpeg?auto=compress&cs=tinysrgb&w=1200',
  bedroom1: 'https://images.pexels.com/photos/6585757/pexels-photo-6585757.jpeg?auto=compress&cs=tinysrgb&w=1200',
  bedroom2: 'https://images.pexels.com/photos/6480209/pexels-photo-6480209.jpeg?auto=compress&cs=tinysrgb&w=1200',
  bedroom3: 'https://images.pexels.com/photos/8092386/pexels-photo-8092386.jpeg?auto=compress&cs=tinysrgb&w=1200',
  bedroom4: 'https://images.pexels.com/photos/6585740/pexels-photo-6585740.jpeg?auto=compress&cs=tinysrgb&w=1200',
  wardrobe1: 'https://images.pexels.com/photos/6580406/pexels-photo-6580406.jpeg?auto=compress&cs=tinysrgb&w=1200',
  wardrobe2: 'https://images.pexels.com/photos/8146203/pexels-photo-8146203.jpeg?auto=compress&cs=tinysrgb&w=1200',
  wardrobe3: 'https://images.pexels.com/photos/8134812/pexels-photo-8134812.jpeg?auto=compress&cs=tinysrgb&w=1200',
  wardrobe4: 'https://images.pexels.com/photos/6587821/pexels-photo-6587821.jpeg?auto=compress&cs=tinysrgb&w=1200',
  door1: 'https://images.pexels.com/photos/8134757/pexels-photo-8134757.jpeg?auto=compress&cs=tinysrgb&w=1200',
  door2: 'https://images.pexels.com/photos/8134755/pexels-photo-8134755.jpeg?auto=compress&cs=tinysrgb&w=1200',
  door3: 'https://images.pexels.com/photos/7166935/pexels-photo-7166935.jpeg?auto=compress&cs=tinysrgb&w=1200',
  door4: 'https://images.pexels.com/photos/7166941/pexels-photo-7166941.jpeg?auto=compress&cs=tinysrgb&w=1200',
  furniture1: 'https://images.pexels.com/photos/5974327/pexels-photo-5974327.jpeg?auto=compress&cs=tinysrgb&w=1200',
  furniture2: 'https://images.pexels.com/photos/6790066/pexels-photo-6790066.jpeg?auto=compress&cs=tinysrgb&w=1200',
  furniture3: 'https://images.pexels.com/photos/37145331/pexels-photo-37145331.jpeg?auto=compress&cs=tinysrgb&w=1200',
  office1: 'https://images.pexels.com/photos/6934239/pexels-photo-6934239.jpeg?auto=compress&cs=tinysrgb&w=1200',
  office2: 'https://images.pexels.com/photos/7511748/pexels-photo-7511748.jpeg?auto=compress&cs=tinysrgb&w=1200',
  office3: 'https://images.pexels.com/photos/35058546/pexels-photo-35058546.jpeg?auto=compress&cs=tinysrgb&w=1200',
  commercial1: 'https://images.pexels.com/photos/31071253/pexels-photo-31071253.jpeg?auto=compress&cs=tinysrgb&w=1200',
  commercial2: 'https://images.pexels.com/photos/20436149/pexels-photo-20436149.jpeg?auto=compress&cs=tinysrgb&w=1200',
  commercial3: 'https://images.pexels.com/photos/7508750/pexels-photo-7508750.jpeg?auto=compress&cs=tinysrgb&w=1200',
  livingRoom1: 'https://images.pexels.com/photos/32421758/pexels-photo-32421758.png?auto=compress&cs=tinysrgb&w=1200',
  livingRoom2: 'https://images.pexels.com/photos/12441654/pexels-photo-12441654.jpeg?auto=compress&cs=tinysrgb&w=1200',
  woodTexture1: 'https://images.pexels.com/photos/36081877/pexels-photo-36081877.jpeg?auto=compress&cs=tinysrgb&w=1200',
  woodTexture2: 'https://images.pexels.com/photos/301717/pexels-photo-301717.jpeg?auto=compress&cs=tinysrgb&w=1200',
  woodTexture3: 'https://images.pexels.com/photos/131639/pexels-photo-131639.jpeg?auto=compress&cs=tinysrgb&w=1200',
  craft1: 'https://images.pexels.com/photos/30907890/pexels-photo-30907890.jpeg?auto=compress&cs=tinysrgb&w=1200',
  craft2: 'https://images.pexels.com/photos/37358117/pexels-photo-37358117.jpeg?auto=compress&cs=tinysrgb&w=1200',
  heroMain: 'https://images.pexels.com/photos/8143944/pexels-photo-8143944.jpeg?auto=compress&cs=tinysrgb&w=1920',
  heroAlt: 'https://images.pexels.com/photos/6580406/pexels-photo-6580406.jpeg?auto=compress&cs=tinysrgb&w=1920',
};

export const heroImages = [
  'https://images.pexels.com/photos/8143944/pexels-photo-8143944.jpeg?auto=compress&cs=tinysrgb&w=1920',
  'https://images.pexels.com/photos/6580406/pexels-photo-6580406.jpeg?auto=compress&cs=tinysrgb&w=1920',
  'https://images.pexels.com/photos/32421758/pexels-photo-32421758.png?auto=compress&cs=tinysrgb&w=1920',
  'https://images.pexels.com/photos/8134757/pexels-photo-8134757.jpeg?auto=compress&cs=tinysrgb&w=1920',
];

export const projects: Project[] = [
  {
    slug: 'modern-wooden-kitchen-01',
    title: { ar: 'مطبخ خشبي عصري', he: 'מטבח עץ מודרני', en: 'Modern Wooden Kitchen' },
    category: 'kitchens',
    description: {
      ar: 'مطبخ مخصص بتصميم عصري يجمع بين الدفء والأناقة، مع خزائن خشبية وأسطح رخامية.',
      he: 'מטבח מותאם אישית עם עיצוב מודרני המשלב חום ואלגנטיות, עם ארונות עץ ומשטחי שיש.',
      en: 'A custom kitchen with a modern design combining warmth and elegance, featuring wooden cabinets and marble countertops.',
    },
    images: [projectImages.kitchen1, projectImages.kitchen2, projectImages.kitchen3],
    materials: ['MDF', 'Veneer', 'Natural Wood'],
    isDemo: true,
  },
  {
    slug: 'luxury-kitchen-island-02',
    title: { ar: 'مطبخ فاخر بجزيرة وسطية', he: 'מטבח יוקרה עם אי מרכזי', en: 'Luxury Kitchen with Island' },
    category: 'kitchens',
    description: {
      ar: 'مطبخ فاخر بجزيرة وسطية أنيقة، يجمع بين الوظيفية والجمال الفائق.',
      he: 'מטבח יוקרה עם אי מרכזי אלגנטי המשלב פונקציונליות ויופי יוצא דופן.',
      en: 'A luxury kitchen with an elegant central island, combining functionality and exceptional beauty.',
    },
    images: [projectImages.kitchen2, projectImages.kitchen4, projectImages.kitchen5],
    materials: ['HPL', 'Acrylic', 'Glass'],
    isDemo: true,
  },
  {
    slug: 'serene-bedroom-suite-03',
    title: { ar: 'غرفة نوم هادئة', he: 'חדר שינה שליו', en: 'Serene Bedroom Suite' },
    category: 'bedrooms',
    description: {
      ar: 'غرفة نوم مخصصة بتصميم هادئ وألوان دافئة، تمنح الراحة والاسترخاء.',
      he: 'חדר שינה מותאם אישית עם עיצוב שליו וגוונים חמים המעניקים נוחות ורגיעה.',
      en: 'A custom bedroom with a calm design and warm tones, providing comfort and relaxation.',
    },
    images: [projectImages.bedroom1, projectImages.bedroom2, projectImages.bedroom3],
    materials: ['MDF', 'Veneer', 'Melamine'],
    isDemo: true,
  },
  {
    slug: 'elegant-master-bedroom-04',
    title: { ar: 'غرفة نوم رئيسية أنيقة', he: 'חדר שינה ראשי אלגנטי', en: 'Elegant Master Bedroom' },
    category: 'bedrooms',
    description: {
      ar: 'غرفة نوم رئيسية بتصميم أنيق ومتكامل، مع خزائن مدمجة وإضارة مدروسة.',
      he: 'חדר שינה ראשי עם עיצוב אלגנטי ומקיף, עם ארונות מובנים ותאורה מחושבת.',
      en: 'A master bedroom with an elegant and complete design, featuring built-in wardrobes and thoughtful lighting.',
    },
    images: [projectImages.bedroom2, projectImages.bedroom4, projectImages.bedroom1],
    materials: ['Natural Wood', 'Veneer'],
    isDemo: true,
  },
  {
    slug: 'walk-in-closet-luxury-05',
    title: { ar: 'غرفة ملابس فاخرة', he: 'חדר ארונות יוקרתי', en: 'Luxury Walk-in Closet' },
    category: 'wardrobes',
    description: {
      ar: 'غرفة ملابس فاخرة بتنظيم مثالي وإضاءة أنيقة، مصممة للاستخدام العملي والجمالي.',
      he: 'חדר ארונות יוקרתי עם ארגון מושלם ותאורה אלגנטית, מעוצב לשימוש פרקטי ואסתטי.',
      en: 'A luxury walk-in closet with perfect organization and elegant lighting, designed for practical and aesthetic use.',
    },
    images: [projectImages.wardrobe1, projectImages.wardrobe2, projectImages.wardrobe3],
    materials: ['MDF', 'Acrylic', 'Glass'],
    isDemo: true,
  },
  {
    slug: 'built-in-wardrobe-06',
    title: { ar: 'خزانة مدمجة عصرية', he: 'ארון מובנה מודרני', en: 'Modern Built-in Wardrobe' },
    category: 'wardrobes',
    description: {
      ar: 'خزانة مدمجة بتصميم عصري وحلول تخزين ذكية، تستغل المساحة بأفضل شكل.',
      he: 'ארון מובנה עם עיצוב מודרני ופתרונות אחסון חכמים המנצלים את השטח בצורה אופטימלית.',
      en: 'A built-in wardrobe with modern design and smart storage solutions, maximizing space utilization.',
    },
    images: [projectImages.wardrobe3, projectImages.wardrobe4, projectImages.wardrobe1],
    materials: ['Melamine', 'MDF'],
    isDemo: true,
  },
  {
    slug: 'elegant-wooden-doors-07',
    title: { ar: 'أبواب خشبية أنيقة', he: 'דלתות עץ אלגנטיות', en: 'Elegant Wooden Doors' },
    category: 'doors',
    description: {
      ar: 'أبواب خشبية مخصصة بتصميم أنيق وتشطيب فاخر، تضيف لمسة جمالية للمساحات.',
      he: 'דלתות עץ מותאמות אישית עם עיצוב אלגנטי וגימור יוקרתי המוסיפים נגיעה אסתטית לחללים.',
      en: 'Custom wooden doors with elegant design and premium finishing, adding aesthetic appeal to spaces.',
    },
    images: [projectImages.door1, projectImages.door2, projectImages.door3],
    materials: ['Natural Wood', 'Veneer'],
    isDemo: true,
  },
  {
    slug: 'modern-interior-doors-08',
    title: { ar: 'أبواب داخلية عصرية', he: 'דלתות פנים מודרניות', en: 'Modern Interior Doors' },
    category: 'doors',
    description: {
      ar: 'أبواب داخلية بتصميم عصري وخطوط نظيفة، تناسب المساحات المعاصرة.',
      he: 'דלתות פנים עם עיצוב מודרני וקווים נקיים המתאימים לחללים עכשוויים.',
      en: 'Interior doors with modern design and clean lines, suited for contemporary spaces.',
    },
    images: [projectImages.door2, projectImages.door4, projectImages.door1],
    materials: ['MDF', 'Melamine'],
    isDemo: true,
  },
  {
    slug: 'custom-wood-furniture-09',
    title: { ar: 'أثاث خشبي مخصص', he: 'ריהוט עץ מותאם', en: 'Custom Wood Furniture' },
    category: 'furniture',
    description: {
      ar: 'قطع أثاث فريدة مصممة ومصنّعة يدوياً بأعلى معايير الجودة والحرفية.',
      he: 'פריטי ריהוט ייחודיים המעוצבים ומיוצרים ידנית בסטנדרטים הגבוהים ביותר של איכות ומלאכה.',
      en: 'Unique furniture pieces designed and handcrafted to the highest standards of quality and craftsmanship.',
    },
    images: [projectImages.furniture1, projectImages.furniture2, projectImages.furniture3],
    materials: ['Natural Wood', 'Metal'],
    isDemo: true,
  },
  {
    slug: 'executive-office-space-10',
    title: { ar: 'مكتب تنفيذي', he: 'משרד מנהלים', en: 'Executive Office Space' },
    category: 'commercial',
    description: {
      ar: 'مساحة مكتبية تنفيذية بتصميم احترافي وأثاث مخصص يعكس الهوية المؤسسية.',
      he: 'חלל משרדי מנהלים עם עיצוב מקצועי וריהוט מותאם המשקף את הזהות הארגונית.',
      en: 'An executive office space with professional design and custom furniture reflecting corporate identity.',
    },
    images: [projectImages.office1, projectImages.office2, projectImages.office3],
    materials: ['MDF', 'Veneer', 'Metal'],
    isDemo: true,
  },
  {
    slug: 'restaurant-interior-11',
    title: { ar: 'تصميم داخلي لمطعم', he: 'עיצוב פנים למסעדה', en: 'Restaurant Interior' },
    category: 'commercial',
    description: {
      ar: 'تصميم داخلي لمطعم يجمع بين الأجواء الدافئة والجمال العصري، مع أثاث خشبي مخصص.',
      he: 'עיצוב פנים למסעדה המשלב אווירה חמה ויופי מודרני, עם ריהוט עץ מותאם.',
      en: 'A restaurant interior design combining warm ambiance and modern beauty, with custom wood furniture.',
    },
    images: [projectImages.commercial1, projectImages.commercial2, projectImages.commercial3],
    materials: ['Natural Wood', 'MDF', 'Metal'],
    isDemo: true,
  },
  {
    slug: 'luxury-living-room-12',
    title: { ar: 'غرفة معيشة فاخرة', he: 'סלון יוקרתי', en: 'Luxury Living Room' },
    category: 'furniture',
    description: {
      ar: 'غرفة معيشة بتصميم فاخر وأثاث مخصص، تمنح المساحة دفئاً وأناقة استثنائية.',
      he: 'סלון עם עיצוב יוקרתי וריהוט מותאם המעניק לחלל חום ואלגנטיות יוצאת דופן.',
      en: 'A living room with luxury design and custom furniture, giving the space warmth and exceptional elegance.',
    },
    images: [projectImages.livingRoom1, projectImages.livingRoom2, projectImages.commercial1],
    materials: ['Natural Wood', 'Veneer', 'Glass'],
    isDemo: true,
  },
];

export const materials: Material[] = [
  {
    slug: 'mdf',
    name: { ar: 'MDF', he: 'MDF', en: 'MDF' },
    description: {
      ar: 'لوح ألياف خشبية متوسط الكثافة، مثالي للأسطح المستوية والتصاميم المعقدة.',
      he: 'לוח סיבים בצפיפות בינונית, אידיאלי למשטחים חלקים ועיצובים מורכבים.',
      en: 'Medium-density fiberboard, ideal for smooth surfaces and complex designs.',
    },
    characteristics: {
      ar: 'سطح ناعم، سهل القطع والتشكيل، مقاوم للتشوه.',
      he: 'משטח חלק, קל לחיתוך ועיצוב, עמיד לעיוות.',
      en: 'Smooth surface, easy to cut and shape, warp-resistant.',
    },
    applications: {
      ar: 'الخزائن، الأبواب، الأرفف، الأثاث المخصص.',
      he: 'ארונות, דלתות, מדפים, ריהוט מותאם.',
      en: 'Cabinets, doors, shelves, custom furniture.',
    },
    finishes: {
      ar: 'قشرة خشبية، أكريليك، ميلامين، طلاء.',
      he: 'ציפוי עץ, אקריליק, מלמין, צבע.',
      en: 'Veneer, acrylic, melamine, paint.',
    },
    image: projectImages.woodTexture1,
  },
  {
    slug: 'hpl',
    name: { ar: 'HPL', he: 'HPL', en: 'HPL' },
    description: {
      ar: 'رقائق ضغط عالي، مقاومة للخدش والحرارة والرطوبة.',
      he: 'שכבות לחץ גבוה, עמידות לשריטות, חום ולחות.',
      en: 'High-pressure laminate, resistant to scratches, heat, and moisture.',
    },
    characteristics: {
      ar: 'مقاوم للخدش، مقاوم للحرارة، سهل التنظيف، متين.',
      he: 'עמיד לשריטות, עמיד לחום, קל לניקוי, עמיד.',
      en: 'Scratch-resistant, heat-resistant, easy to clean, durable.',
    },
    applications: {
      ar: 'المطابخ، الحمامات، الأسطح العملية.',
      he: 'מטבחים, חדרי אמבטיה, משטחי עבודה.',
      en: 'Kitchens, bathrooms, work surfaces.',
    },
    finishes: {
      ar: 'مطفي، لامع، خشبي، ملون.',
      he: 'מט, מבריק, עץ, צבעוני.',
      en: 'Matte, gloss, wood, colored.',
    },
    image: projectImages.woodTexture2,
  },
  {
    slug: 'acrylic',
    name: { ar: 'أكريليك', he: 'אקריליק', en: 'Acrylic' },
    description: {
      ar: 'سطح لامع عالي الجودة بلمسة فاخرة وعمق بصري استثنائي.',
      he: 'משטח מבריק באיכות גבוהה עם מגע יוקרתי ועומק ויזואלי יוצא דופן.',
      en: 'High-gloss surface with a luxurious touch and exceptional visual depth.',
    },
    characteristics: {
      ar: 'لمعان عالي، مقاوم للخدش، ألوان غنية، سهل التنظيف.',
      he: 'ברק גבוה, עמיד לשריטות, צבעים עשירים, קל לניקוי.',
      en: 'High gloss, scratch-resistant, rich colors, easy to clean.',
    },
    applications: {
      ar: 'المطابخ، الخزائن، الأثاث الحديث.',
      he: 'מטבחים, ארונות, ריהוט מודרני.',
      en: 'Kitchens, wardrobes, modern furniture.',
    },
    finishes: {
      ar: 'لامع عالي، ألوان متعددة.',
      he: 'מבריק גבוה, מגוון צבעים.',
      en: 'High gloss, multiple colors.',
    },
    image: projectImages.woodTexture3,
  },
  {
    slug: 'veneer',
    name: { ar: 'قشرة خشبية', he: 'ציפוי עץ', en: 'Veneer' },
    description: {
      ar: 'قشرة خشب طبيعي تمنح مظهراً أصيلاً ودفئاً للأسطح.',
      he: 'ציפוי עץ טבעי המעניק מראה אותנטי וחום למשטחים.',
      en: 'Natural wood veneer providing an authentic look and warmth to surfaces.',
    },
    characteristics: {
      ar: 'مظهر طبيعي، أنماط خشبية فريدة، لمسة دافئة.',
      he: 'מראה טבעי, דפוסי עץ ייחודיים, מגע חם.',
      en: 'Natural appearance, unique wood patterns, warm touch.',
    },
    applications: {
      ar: 'الأثاث الفاخر، الأبواب، المكاتب.',
      he: 'ריהוט יוקרה, דלתות, משרדים.',
      en: 'Luxury furniture, doors, offices.',
    },
    finishes: {
      ar: 'مطفي، لامع، شمع، زيت.',
      he: 'מט, מבריק, שעווה, שמן.',
      en: 'Matte, gloss, wax, oil.',
    },
    image: projectImages.woodTexture1,
  },
  {
    slug: 'melamine',
    name: { ar: 'ميلامين', he: 'מלמין', en: 'Melamine' },
    description: {
      ar: 'سطح متين وسهل الصيانة بأسعار منافسة، متوفر بألوان وتشطيبات متعددة.',
      he: 'משטח עמיד וקל לתחזוקה במחיר נגיש, זמין במגוון צבעים וגימורים.',
      en: 'Durable and easy-to-maintain surface at competitive prices, available in multiple colors and finishes.',
    },
    characteristics: {
      ar: 'مقاوم للخدش، سهل التنظيف، اقتصادي.',
      he: 'עמיד לשריטות, קל לניקוי, כלכלי.',
      en: 'Scratch-resistant, easy to clean, economical.',
    },
    applications: {
      ar: 'الخزائن، الأرفف، المساحات التجارية.',
      he: 'ארונות, מדפים, חללים מסחריים.',
      en: 'Wardrobes, shelves, commercial spaces.',
    },
    finishes: {
      ar: 'مطفي، خشبي، ملون، نسيجي.',
      he: 'מט, עץ, צבעוני, מרקם.',
      en: 'Matte, wood, colored, textured.',
    },
    image: projectImages.woodTexture2,
  },
  {
    slug: 'natural-wood',
    name: { ar: 'خشب طبيعي', he: 'עץ טבעי', en: 'Natural Wood' },
    description: {
      ar: 'خشب صلب بألوان طبيعية دافئة، يمنح المساحات شخصية فريدة.',
      he: 'עץ קשה בגוונים טבעיים חמים המעניק לחללים אישיות ייחודית.',
      en: 'Solid wood with warm natural tones, giving spaces a unique character.',
    },
    characteristics: {
      ar: 'متانة عالية، مظهر طبيعي، يدوم طويلاً.',
      he: 'עמידות גבוהה, מראה טבעי, אורך חיים ארוך.',
      en: 'High durability, natural appearance, long-lasting.',
    },
    applications: {
      ar: 'الأثاث الفاخر، الأبواب، الأرضيات.',
      he: 'ריהוט יוקרה, דלתות, רצפות.',
      en: 'Luxury furniture, doors, flooring.',
    },
    finishes: {
      ar: 'زيت، شمع، ورنيش، مطفي.',
      he: 'שמן, שעווה, לכה, מט.',
      en: 'Oil, wax, varnish, matte.',
    },
    image: projectImages.woodTexture3,
  },
  {
    slug: 'glass',
    name: { ar: 'زجاج', he: 'זכוכית', en: 'Glass' },
    description: {
      ar: 'لمسة عصرية وإضاءة للمساحات، متوفر بأنواع وشفافيات متعددة.',
      he: 'נגיעה מודרנית ותאורה לחללים, זמינה בסוגים ושקיפויות מרובים.',
      en: 'A modern touch and illumination for spaces, available in multiple types and transparencies.',
    },
    characteristics: {
      ar: 'شفاف، عصري، يوسع المساحات بصرياً.',
      he: 'שקוף, מודרני, מרחיב חללים ויזואלית.',
      en: 'Transparent, modern, visually expands spaces.',
    },
    applications: {
      ar: 'الأبواب الزجاجية، الواجهات، الأرفف.',
      he: 'דלתות זכוכית, חזיתות, מדפים.',
      en: 'Glass doors, facades, shelves.',
    },
    finishes: {
      ar: 'شفاف، مصنفر، ملون، عاكس.',
      he: 'שקוף, מטושטש, צבעוני, מחזיר.',
      en: 'Clear, frosted, colored, mirrored.',
    },
    image: projectImages.woodTexture1,
  },
  {
    slug: 'metal',
    name: { ar: 'معدن', he: 'מתכת', en: 'Metal' },
    description: {
      ar: 'تفاصيل معدنية تضيف المتانة والأناقة، مثالية للتصاميم المعاصرة.',
      he: 'פרטי מתכת המוסיפים עמידות ואלגנטיות, אידיאליים לעיצובים עכשוויים.',
      en: 'Metal details adding durability and elegance, ideal for contemporary designs.',
    },
    characteristics: {
      ar: 'متانة عالية، مقاوم، تشطيبات متعددة.',
      he: 'עמידות גבוהה, חזק, מגוון גימורים.',
      en: 'High durability, strong, multiple finishes.',
    },
    applications: {
      ar: 'الإكسسوارات، المقابض، الأرجل، الهياكل.',
      he: 'אביזרים, ידיות, רגליים, מסגרות.',
      en: 'Accessories, handles, legs, frames.',
    },
    finishes: {
      ar: 'مطلي، مصقول، أسود، ذهبي.',
      he: 'מצופה, מלוטש, שחור, זהב.',
      en: 'Coated, polished, black, gold.',
    },
    image: projectImages.woodTexture2,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'DEMO Customer 1',
    rating: 5,
    review: {
      ar: 'تجربة رائعة مع Nora Group. الجودة والاحترافية فاقت توقعاتي. المطبخ أصبح تحفة فنية في منزلي.',
      he: 'חוויה מדהימה עם Nora Group. האיכות והמקצועיות עלו על ציפיותיי. המטבח הפך ליצירת אמנות בביתי.',
      en: 'An amazing experience with Nora Group. The quality and professionalism exceeded my expectations. The kitchen became a work of art in my home.',
    },
    project: { ar: 'مطبخ مخصص', he: 'מטבח מותאם', en: 'Custom Kitchen' },
    isDemo: true,
  },
  {
    id: '2',
    name: 'DEMO Customer 2',
    rating: 5,
    review: {
      ar: 'فريق محترف ودقيق في المواعيد. غرفة الملابس التي صمموها لي غيّرت حياتي اليومية تماماً.',
      he: 'צוות מקצועי ומדויק בלוחות זמנים. חדר הארונות שעיצבו לי שינה לחלוטין את שגרת היומיום שלי.',
      en: 'A professional and punctual team. The walk-in closet they designed for me completely changed my daily life.',
    },
    project: { ar: 'غرفة ملابس', he: 'חדר ארונות', en: 'Walk-in Closet' },
    isDemo: true,
  },
  {
    id: '3',
    name: 'DEMO Customer 3',
    rating: 5,
    review: {
      ar: 'اهتمام مذهل بالتفاصيل. كل قطعة في غرفة النوم مصنوعة بإتقان لا يصدق. أنصح بشدة.',
      he: 'תשומת לב מדהימה לפרטים. כל פריט בחדר השינה מיוצר במיומנות לא ייאמן. ממליץ בחום.',
      en: 'Amazing attention to detail. Every piece in the bedroom is crafted with incredible precision. Highly recommended.',
    },
    project: { ar: 'غرفة نوم', he: 'חדר שינה', en: 'Bedroom' },
    isDemo: true,
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: 'choosing-right-kitchen-materials',
    title: {
      ar: 'كيف تختار الخامات المناسبة لمطبخك',
      he: 'איך לבחור את החומרים הנכונים למטבח שלך',
      en: 'How to Choose the Right Materials for Your Kitchen',
    },
    excerpt: {
      ar: 'دليل شامل لاختيار خامات المطابخ، من MDF إلى الخشب الطبيعي، ومميزات كل نوع.',
      he: 'מדריך מקיף לבחירת חומרי מטבח, מ-MDF ועד עץ טבעי, והיתרונות של כל סוג.',
      en: 'A comprehensive guide to choosing kitchen materials, from MDF to natural wood, and the advantages of each type.',
    },
    content: {
      ar: 'يعتبر اختيار الخامات المناسبة للمطبخ من أهم القرارات في تصميم المنزل. كل خامة لها مميزاتها الخاصة...',
      he: 'בחירת החומרים הנכונים למטבח היא אחת ההחלטות החשובות בעיצוב הבית. לכל חומר יש את היתרונות שלו...',
      en: 'Choosing the right materials for your kitchen is one of the most important decisions in home design. Each material has its own advantages...',
    },
    category: 'kitchens',
    author: 'Nora Group Team',
    date: '2025-01-15',
    image: projectImages.kitchen1,
    isDemo: true,
  },
  {
    slug: 'modern-wardrobe-design-trends',
    title: {
      ar: 'اتجاهات تصميم الخزائن العصرية',
      he: 'מגמות עיצוב ארונות מודרניים',
      en: 'Modern Wardrobe Design Trends',
    },
    excerpt: {
      ar: 'استكشف أحدث اتجاهات تصميم الخزائن وغرف الملابس لعام 2025.',
      he: 'גלו את מגמות עיצוב הארונות וחדרי הארונות האחרונות ל-2025.',
      en: 'Explore the latest wardrobe and walk-in closet design trends for 2025.',
    },
    content: {
      ar: 'تتطور تصاميم الخزائن باستمرار لتلبي احتياجات المساحات الحديثة. من التصاميم المدمجة إلى غرف الملابس الفاخرة...',
      he: 'עיצובי ארונות מתפתחים ללא הרף כדי לענות על צרכי חללים מודרניים. מעיצובים מובנים ועד חדרי ארונות יוקרתיים...',
      en: 'Wardrobe designs continue to evolve to meet the needs of modern spaces. From built-in designs to luxury walk-in closets...',
    },
    category: 'trends',
    author: 'Nora Group Team',
    date: '2025-02-20',
    image: projectImages.wardrobe1,
    isDemo: true,
  },
  {
    slug: 'maintaining-wood-furniture',
    title: {
      ar: 'كيفية العناية بالأثاث الخشبي',
      he: 'איך לתחזק ריהוט עץ',
      en: 'How to Maintain Wood Furniture',
    },
    excerpt: {
      ar: 'نصائح عملية للحفاظ على جمال ومتانة أثاثك الخشبي لسنوات قادمة.',
      he: 'טיפים פרקטיים לשמירת היופי והעמידות של ריהוט העץ שלך לשנים קדימה.',
      en: 'Practical tips to preserve the beauty and durability of your wood furniture for years to come.',
    },
    content: {
      ar: 'الأثاث الخشبي استثمار طويل الأمد، ومع العناية المناسبة يمكن أن يدوم لأجيال...',
      he: 'ריהוט עץ הוא השקעה לטווח ארוך, ועם טיפול נכון יכול להחזיק מעמד לדורות...',
      en: 'Wood furniture is a long-term investment, and with proper care it can last for generations...',
    },
    category: 'maintenance',
    author: 'Nora Group Team',
    date: '2025-03-10',
    image: projectImages.furniture1,
    isDemo: true,
  },
  {
    slug: 'interior-design-principles',
    title: {
      ar: 'مبادئ التصميم الداخلي الأساسية',
      he: 'עקרונות יסוד בעיצוב פנים',
      en: 'Fundamental Interior Design Principles',
    },
    excerpt: {
      ar: 'تعرّف على المبادئ الأساسية للتصميم الداخلي وكيفية تطبيقها في مساحاتك.',
      he: 'הכירו את העקרונות הבסיסיים של עיצוב פנים ואיך ליישם אותם בחללים שלכם.',
      en: 'Learn the fundamental principles of interior design and how to apply them in your spaces.',
    },
    content: {
      ar: 'التصميم الداخلي ليس مجرد تزيين، بل هو فن وعلم يجمع بين الجمال والوظيفة...',
      he: 'עיצוב פנים אינו רק קישוט, אלא אמנות ומדע המשלבים יופי ופונקציונליות...',
      en: 'Interior design is not just decoration, but an art and science combining beauty and function...',
    },
    category: 'design',
    author: 'Nora Group Team',
    date: '2025-04-05',
    image: projectImages.livingRoom1,
    isDemo: true,
  },
];

export const faqItems: FAQItem[] = [
  {
    id: '1',
    category: 'general',
    question: { ar: 'ما هي مدة تنفيذ المشروع؟', he: 'מהי משך ביצוע הפרויקט?', en: 'How long does a project take?' },
    answer: { ar: 'تختلف مدة التنفيذ حسب نوع وحجم المشروع. نقدم جدولاً زمنياً تفصيلياً بعد الاستشارة الأولى.', he: 'משך הביצוע משתנה בהתאם לסוג וגודל הפרויקט. אנו מספקים לוח זמנים מפורט לאחר הייעוץ הראשון.', en: 'Project duration varies depending on the type and scope. We provide a detailed timeline after the initial consultation.' },
  },
  {
    id: '2',
    category: 'general',
    question: { ar: 'هل تقدمون ضماناً على الأعمال؟', he: 'האם אתם מספקים אחריות על העבודות?', en: 'Do you provide a warranty on your work?' },
    answer: { ar: '[معلومات الضمان — أضف التفاصيل هنا]', he: '[מידע על אחריות — הוסף פרטים כאן]', en: '[Warranty information — add details here]' },
  },
  {
    id: '3',
    category: 'services',
    question: { ar: 'ما الخدمات التي تقدمونها؟', he: 'אילו שירותים אתם מספקים?', en: 'What services do you offer?' },
    answer: { ar: 'نقدم تصميم وتصنيع المطابخ، غرف النوم، الخزائن، غرف الملابس، الأبواب، الأثاث المخصص، المكاتب، والمشاريع التجارية.', he: 'אנו מציעים עיצוב וייצור של מטבחים, חדרי שינה, ארונות, חדרי ארונות, דלתות, ריהוט מותאם, משרדים ופרויקטים מסחריים.', en: 'We offer design and manufacturing of kitchens, bedrooms, wardrobes, walk-in closets, doors, custom furniture, offices, and commercial projects.' },
  },
  {
    id: '4',
    category: 'services',
    question: { ar: 'هل تقدمون خدمة التصميم ثلاثي الأبعاد؟', he: 'האם אתם מציעים שירות עיצוב תלת-ממדי?', en: 'Do you offer 3D design services?' },
    answer: { ar: 'نعم، نقدم تصاميم ثلاثية الأبعاد لمساعدتك على رؤية مشروعك قبل التنفيذ.', he: 'כן, אנו מציעים עיצובים תלת-ממדיים כדי לעזור לך לראות את הפרויקט לפני הביצוע.', en: 'Yes, we provide 3D designs to help you visualize your project before execution.' },
  },
  {
    id: '5',
    category: 'materials',
    question: { ar: 'ما الخامات المتاحة؟', he: 'אילו חומרים זמינים?', en: 'What materials are available?' },
    answer: { ar: 'نوفر تشكيلة واسعة من الخامات تشمل MDF، HPL، الأكريليك، القشرة الخشبية، الميلامين، الخشب الطبيعي، الزجاج، والمعدن.', he: 'אנו מספקים מגוון רחב של חומרים כולל MDF, HPL, אקריליק, ציפוי עץ, מלמין, עץ טבעי, זכוכית ומתכת.', en: 'We offer a wide range of materials including MDF, HPL, Acrylic, Veneer, Melamine, Natural Wood, Glass, and Metal.' },
  },
  {
    id: '6',
    category: 'pricing',
    question: { ar: 'كيف يتم تحديد الأسعار؟', he: 'איך נקבעים המחירים?', en: 'How is pricing determined?' },
    answer: { ar: 'يتم تحديد السعر بناءً على نوع المشروع، الخامات المختارة، الأبعاد، والتصميم. نقدم عرض سعر مفصل بعد الاستشارة.', he: 'המחיר נקבע בהתאם לסוג הפרויקט, החומרים הנבחרים, המידות והעיצוב. אנו מספקים הצעת מחיר מפורטת לאחר הייעוץ.', en: 'Pricing is determined based on project type, selected materials, dimensions, and design. We provide a detailed quote after consultation.' },
  },
  {
    id: '7',
    category: 'pricing',
    question: { ar: 'هل تقديم عرض سعر مجاني؟', he: 'האם הצעת מחיר בחינם?', en: 'Is the quote free?' },
    answer: { ar: 'نعم، نقدم عرض سعر مجاني وبدون التزام. يمكنك طلب عرض السعر عبر موقعنا.', he: 'כן, אנו מציעים הצעת מחיר בחינם וללא התחייבות. ניתן לבקש הצעת מחיר דרך האתר שלנו.', en: 'Yes, we provide a free, no-obligation quote. You can request a quote through our website.' },
  },
  {
    id: '8',
    category: 'manufacturing',
    question: { ar: 'أين يتم التصنيع؟', he: 'היכן מתבצע הייצור?', en: 'Where does manufacturing take place?' },
    answer: { ar: 'يتم التصنيع في ورشتنا المتخصصة بأحدث المعدات والتقنيات.', he: 'הייצור מתבצע בסדנא המתמחה שלנו עם הציוד והטכנולוגיות המתקדמים ביותר.', en: 'Manufacturing takes place in our specialized workshop with the latest equipment and technologies.' },
  },
  {
    id: '9',
    category: 'installation',
    question: { ar: 'هل تقدمون خدمة التركيب؟', he: 'האם אתם מציעים שירות התקנה?', en: 'Do you offer installation services?' },
    answer: { ar: 'نعم، فريقنا المتخصص يقوم بالتركيب في موقعك باحترافية وكفاءة.', he: 'כן, הצוות המומחה שלנו מבצע התקנה באתר שלך במקצועיות וביעילות.', en: 'Yes, our specialized team performs professional and efficient on-site installation.' },
  },
  {
    id: '10',
    category: 'installation',
    question: { ar: 'كم يستغرق التركيب؟', he: 'כמה זמן לוקח ההתקנה?', en: 'How long does installation take?' },
    answer: { ar: 'تختلف مدة التركيب حسب حجم وتعقيد المشروع، ونلتزم بالجدول الزمني المتفق عليه.', he: 'משך ההתקנה משתנה בהתאם לגודל ומורכבות הפרויקט, ואנו מקפידים על לוח הזמנים המוסכם.', en: 'Installation duration varies based on project size and complexity, and we adhere to the agreed timeline.' },
  },
];

export const processSteps: ProcessStep[] = [
  { number: '01', title: { ar: 'الاستشارة', he: 'ייעוץ', en: 'Consultation' }, description: { ar: 'نستمع لاحتياجاتك ونناقش رؤيتك للمشروع', he: 'אנו מקשיבים לצרכים שלך ודנים בחזון שלך', en: 'We listen to your needs and discuss your vision' }, icon: 'MessageSquare' },
  { number: '02', title: { ar: 'أخذ المقاسات', he: 'מדידות', en: 'Measurement' }, description: { ar: 'نزور الموقع ونأخذ المقاسات بدقة', he: 'אנו מבקרים באתר ולוקחים מדידות מדויקות', en: 'We visit the site and take precise measurements' }, icon: 'Ruler' },
  { number: '03', title: { ar: 'التصميم', he: 'עיצוב', en: 'Design' }, description: { ar: 'نقدم تصاميم ثلاثية الأبعاد لرؤية مشروعك', he: 'אנו מציגים עיצובים תלת-ממדיים', en: 'We present 3D designs to visualize your project' }, icon: 'PenTool' },
  { number: '04', title: { ar: 'اعتماد التصميم', he: 'אישור עיצוב', en: 'Design Approval' }, description: { ar: 'نراجع التصميم معك ونجري التعديلات اللازمة', he: 'אנו סוקרים את העיצוב ומבצעים שינויים', en: 'We review the design with you and make adjustments' }, icon: 'CheckCircle' },
  { number: '05', title: { ar: 'التصنيع', he: 'ייצור', en: 'Manufacturing' }, description: { ar: 'نبدأ التصنيع بأحدث المعدات والتقنيات', he: 'אנו מתחילים בייצור עם ציוד מתקדם', en: 'We begin manufacturing with the latest equipment' }, icon: 'Hammer' },
  { number: '06', title: { ar: 'التركيب', he: 'התקנה', en: 'Installation' }, description: { ar: 'فريقنا يقوم بالتركيب في موقعك باحترافية', he: 'הצוות שלנו מבצע התקנה מקצועית', en: 'Our team performs professional on-site installation' }, icon: 'Wrench' },
  { number: '07', title: { ar: 'التسليم', he: 'מסירה', en: 'Delivery' }, description: { ar: 'نسلمك المشروع جاهزاً بأعلى جودة', he: 'אנו מוסרים את הפרויקט מוכן באיכות הגבוהה', en: 'We deliver your project ready at the highest quality' }, icon: 'PackageCheck' },
];
