import { CONTACT_DEFAULTS } from '@/lib/constants';
import { images } from '@/lib/content/images';
import type { NavLabels, SiteContent } from '@/lib/content/types';
import { L } from '@/lib/i18n/locale';

const navHe: NavLabels = {
  home: 'דף הבית',
  about: 'אודות',
  services: 'שירותים',
  projects: 'הפרויקטים',
  materials: 'חומרים',
  howWeWork: 'איך אנחנו עובדים',
  testimonials: 'המלצות',
  blog: 'בלוג',
  faq: 'שאלות נפוצות',
  contact: 'צור קשר',
  callUs: 'התקשרו',
  whatsapp: 'וואטסאפ',
  viewWork: 'צפה בעבודות',
  learnMore: 'למידע נוסף',
  viewAll: 'הצג הכל',
  viewProject: 'צפה בפרויקט',
  readMore: 'קרא עוד',
  backHome: 'חזרה לדף הבית',
  all: 'הכל',
};

const navAr: NavLabels = {
  home: 'الرئيسية',
  about: 'من نحن',
  services: 'خدماتنا',
  projects: 'أعمالنا',
  materials: 'الخامات',
  howWeWork: 'طريقة العمل',
  testimonials: 'آراء العملاء',
  blog: 'المدونة',
  faq: 'الأسئلة الشائعة',
  contact: 'تواصل معنا',
  callUs: 'اتصلوا فينا',
  whatsapp: 'واتساب',
  viewWork: 'استعرض أعمالنا',
  learnMore: 'اعرف أكثر',
  viewAll: 'عرض الكل',
  viewProject: 'عرض المشروع',
  readMore: 'اقرأ المزيد',
  backHome: 'العودة للرئيسية',
  all: 'الكل',
};

const navEn: NavLabels = {
  home: 'Home',
  about: 'About',
  services: 'Services',
  projects: 'Our Work',
  materials: 'Materials',
  howWeWork: 'How We Work',
  testimonials: 'Testimonials',
  blog: 'Blog',
  faq: 'FAQ',
  contact: 'Contact',
  callUs: 'Call us',
  whatsapp: 'WhatsApp',
  viewWork: 'See our work',
  learnMore: 'Learn more',
  viewAll: 'View all',
  viewProject: 'View project',
  readMore: 'Read more',
  backHome: 'Back to home',
  all: 'All',
};

const navRu: NavLabels = {
  home: 'Главная',
  about: 'О нас',
  services: 'Услуги',
  projects: 'Работы',
  materials: 'Материалы',
  howWeWork: 'Как мы работаем',
  testimonials: 'Отзывы',
  blog: 'Блог',
  faq: 'Вопросы',
  contact: 'Контакты',
  callUs: 'Позвонить',
  whatsapp: 'WhatsApp',
  viewWork: 'Смотреть работы',
  learnMore: 'Подробнее',
  viewAll: 'Смотреть всё',
  viewProject: 'Смотреть проект',
  readMore: 'Читать далее',
  backHome: 'На главную',
  all: 'Все',
};

export const seedContent: SiteContent = {
  settings: {
    brandName: CONTACT_DEFAULTS.brandName,
    tagline: L(
      'נגרות ועיצוב פנים',
      'نجارة وتصميم داخلي',
      'Custom carpentry & interior design',
      'Столярные работы и дизайн интерьера',
    ),
    pillars: L(
      'ברוכים הבאים לקבוצת נורה',
      'مرحباً بكم في Nora Group',
      'Welcome to Nora Group',
      '​Добро пожаловать в Nora Group',
    ),
    phoneDisplay: CONTACT_DEFAULTS.phoneDisplay,
    phoneTel: CONTACT_DEFAULTS.phoneTel,
    whatsappE164: CONTACT_DEFAULTS.whatsappE164,
    email: CONTACT_DEFAULTS.email,
    address: L('מגדל עוז', 'مجدال عوز', 'Migdal Oz', 'Мигдаль Оз'),
    workingHours: L(
      'א׳–ה׳ 08:00–17:00',
      'أحد–خميس 08:00–17:00',
      'Sun–Thu 8:00 AM–5:00 PM',
      'Вс–Чт 08:00–17:00',
    ),
    whatsappMessage: L(
      'שלום Nora Group, אשמח לשמוע פרטים על פרויקט.',
      'مرحبا Nora Group، بدي أستفسر عن مشروع.',
      'Hi Nora Group, I would like to ask about a project.',
      'Здравствуйте, Nora Group! Хочу узнать о проекте.',
    ),
    logoUrl: CONTACT_DEFAULTS.logoPath,
    logoDarkUrl: CONTACT_DEFAULTS.logoDarkPath,
    qrUrl: CONTACT_DEFAULTS.qrPath,
    seoTitle: L(
      'Nora Group | נגרות ועיצוב פנים',
      'Nora Group | نجارة وتصميم داخلي',
      'Nora Group | Custom Carpentry & Interiors',
      'Nora Group | Столярка и интерьеры',
    ),
    seoDescription: L(
      'נגרות ועיצוב פנים בהתאמה אישית במגדל עוז — תכנון, ביצוע ואיכות.',
      'نجارة وتصميم داخلي حسب الطلب في مجدال عوز — تخطيط، تنفيذ وجودة.',
      'Custom carpentry and interiors in Migdal Oz — planning, execution, quality.',
      'Столярные работы и интерьеры в Мигдаль Оз — планирование, исполнение, качество.',
    ),
  },
  nav: { he: navHe, ar: navAr, en: navEn, ru: navRu },
  home: {
    heroTitle: L(
      '​חללי עץ המעוצבים בדיוק בשבילך',
      'مساحات خشبية تجسد أسلوب حياتك',
      'Crafted Wood Spaces Made for You',
      'Деревянные пространства, которые ощущаются вашими',
    ),
    heroSubtitle: L(
      'תכנון וייצור בהתאמה אישית — מטבחים, ארונות, רהיטים ופרויקטים מסחריים. תכנון מדויק, ביצוע מקצועי ואיכות ללא פשרות.',
      'تصميم وتصنيع حسب الطلب — من المطابخ و الخزائن حتى الأثاث والمشاريع التجارية. تخطيط دقيق، تنفيذ احترافي وجودة مثالية.',
      'Custom design & manufacturing — from kitchens and wardrobes to furniture and commercial projects. Precision planning, flawless execution, and uncompromising quality.',
      'Дизайн и изготовление на заказ — кухни, шкафы, мебель и коммерческие интерьеры. Точное планирование, безупречное исполнение и безупречное качество.',
    ),
    introEyebrow: L('ברוכים הבאים', ' مرحبا بكم في Nora Group', 'Welcome to Nora Group', 'Добро пожаловать в Nora Group'),
    introTitle: L(
      'חכמות ואיכות בסטנדרט גבוהים',
      'حلول خشبية مخصصة بأعلى معايير الجودة',
      'Custom wood solutions at the highest quality standards',
      'Деревянные решения с высоким уровнем качества',
    ),
    introDescription: L(
      'Nora Group מתמחה בתכנון וייצור פתרונות עץ מות  אמים — מהמדידה הראשונה ועד ההתקנה.',
      'نقدم خدمات تصميم وتصنيع وتركيب الأثاث المخصص وحلول النجارة الداخلية. كل مشروع ننفذه هو انعكاس لشخصيتك واحتياجاتك، من الفكرة الأولى حتى التسليم النهائي.',      'Nora Group specializes in planned, custom wood solutions — from measuring to install.',
      'Nora Group специализируется на деревянных реш  ениях под заказ — от замера до монтажа.',
    ),
    introFeatures: [
      {
        title: L('תכנון מותאם', 'تصميم حسب الطلب', 'Tailored design', 'Дизайн под вас'),
        desc: L(
          'כל פרויקט בהתאמה אישית לפי המידות, הטעם והשימוש שלכם',
          'كل قطعة مصممة خصيصاً لتناسب مساحتك وذوقك',
          'Every piece is designed to fit your space and taste',
          'Каждая деталь спроектирована для вашего пространства и вкуса',
        ),
      },
      {
        title: L('ביצוע מדויק', 'حرفية احترافية', 'Professional craftsmanship', 'Точное исполнение'),
        desc: L(
          'צוות מקצועי ותשומת לב לכל פרט יוצרת איכות ומראה',
          'فريق متخصص بأعلى مستويات الدقة والإتقان والجمال',
          'A professional team with the highest levels of precision and expertise and beauty',
          'Профессиональная команда с высоким уровнем точности и экспертизой и красотой',
        ),
      },
      {
        title: L('חומרים איכותיים', 'خامات ممتازة', 'Quality materials', 'Качественные материалы'),
        desc: L(
          'בחירת חומרים לעמידות ויופי על פרק זמן',
          'نختار أفضل الخامات لضمان الجودة والمتانة والجمال',
          'Materials chosen for durability and lasting beauty',
          'Материалы для долговечности и красоты на долгие годы',
        ),
      },
      {
        title: L('ליווי מלא', 'تنفيذ كامل', 'Complete execution', 'Полное сопровождение'),
        desc: L(
          'מדריך ההתקנה והמשלוח בבית מהיר ופשוט',
          'من التصميم إلى التركيب والتسليم، نتولى كل التفاصيل',
          'From design through installation to completion',
          'От дизайна до монтажа и до доставки',
        ),
      },
    ],
    whyEyebrow: L('למה Nora Group', 'لماذا Nora Group', 'Why Nora Group', 'Почему Nora Group'),
    whyTitle: L(
      'אנחנו נמדדים בפרטים',
      'نتميّز بالتفاصيل',
      'We are measured by the details',
      'Нас оценивают по деталям',
    ),
    whySubtitle: L(
      'אנחנו מקפידים על כל פרט כדי להעניק תוצאות שעולות על הציפיות שלך',
      'نحرص على كل تفصيلة لنقدم نتائج تتجاوز توقعاتك',
      'We pay attention to every detail to deliver results that exceed your expectations',
      'Мы уделяем внимание каждой детали, чтобы предоставить результат, превосходящий ваши ожидания',
    ),
    whyItems: [
      {
        title: L('עיצוב אישי', 'تصميم حسب الطلب', 'Personal design', 'Индивидуальный дизайн'),
        desc: L(
          'מתחילים מהצרכים שלכם, לא מתבנית מוכנה',
          'بنبدأ من احتياجاتكم، مش من قالب جاهز',
          'We start from your needs, not a stock template',
          'Начинаем с ваших потребностей, а не с шаблона',
        ),
      },
      {
        title: L('חומרים נבחרים', 'خامات مختارة', 'Selected materials', 'Отборные материалы'),
        desc: L(
          ' חומרים שעומדים בשימוש יומיומי',
          ' خامات بتتحمل الاستخدام اليومي',
          ' materials that stand up to daily use',
          ' материалы для ежедневной нагрузки',
        ),
      },
      {
        title: L('ייצור מדויק', 'تصنيع دقيق', 'Accurate manufacturing', 'Точное производство'),
        desc: L(
          'חיתוך והרכבה ברמת דיוק גבוהה',
          'قص وتركيب بدقة عالية',
          'Cutting and assembly to a high tolerance',
          'Раскрой и сборка с высокой точностью',
        ),
      },
      {
        title: L('גימור נקי', 'تشطيب نظيف', 'Clean finishing', 'Чистая отделка'),
        desc: L(
          'פרטים קטנים שעושים את ההבדל',
          'تفاصيل صغيرة بتعمل الفرق',
          'Small details that make the difference',
          'Мелочи, которые решают всё',
        ),
      },
      {
        title: L('התקנה מקצועית', 'تركيب محترف', 'Pro installation', 'Профессиональный монтаж'),
        desc: L(
          'צוות שמתקין אצלכם באתר',
          'فريق بركّب عندكم بالموقع',
          'A team that installs on site',
          'Команда монтирует у вас на объекте',
        ),
      },
      {
        title: L('קשר ישיר', 'تواصل مباشر', 'Direct contact', 'Прямая связь'),
        desc: L(
          'שיחה בוואטסאפ או בטלפון — בלי טפסים מיותרים',
          'محادثة واتساب أو اتصال بنا',
          'WhatsApp or a phone call to us',
          'WhatsApp или звонок нам',
        ),
      },
    ],
    processEyebrow: L('תהליך העבודה', 'طريقة العمل', 'Our process', 'Процесс работы'),
    processTitle: L(
      'מהרעיון ועד המסירה',
      'من الفكرة لحد التسليم',
      'From idea to handover',
      'От идеи до сдачи',
    ),
    processSubtitle: L(
      'שבעה שלבים ברורים לשקט נפשי',
      'سبع خطوات واضحة لراحة بال',
      'Seven clear steps for peace of mind',
      'Семь понятных шагов для спокойствия',
    ),
    ctaTitle: L(
      'מוכנים להתחיל פרויקט?',
      'جاهزين لبدء المشروع؟',
      'Ready to start a project?',
      'Готовы начать работу?',
    ),
    ctaSubtitle: L(
      'דברו איתנו בוואטסאפ או בטלפון — נשמח לייעץ',
      'تواصل   معنا عبر واتساب — سنكون سعداء للمساعدة',
      'Message us on WhatsApp or call — we are happy to advise',
      'Напишите в WhatsApp или позвоните — с радостью проконсультируем',
    ),
    heroImages: [images.hero1, images.hero2, images.hero3],
    servicesEyebrow: L('השירותים שלנו', 'خدماتنا', 'Our services', 'Наши услуги'),
    servicesTitle: L(
      'אומנות בעץ ברמה גבוהה',
      'فنون خشبية عالية الجودة',
      'High-quality wood craftsmanship',
      'Высококачественная столярка и изделия из дерева',
    ),
    servicesSubtitle: L(
      'מטבחים, ארונות, ריהוט ועוד — בלי דלתות',
      'مطابخ،  خزائن، أثاث وأكثر',
      'Kitchens, wardrobes, furniture, and more',
      'Кухни, шкафы, мебель и не только',
    ),
    projectsEyebrow: L('העבודות שלנו', 'أعمالنا', 'Our work', 'Наши работы'),
    projectsTitle: L(
      'מהרעיון ועד לתוצאה המושלמת בשטח',
      'أفكار استثنائية تحولت إلى واقع ملموس',
      'Bringing bespoke concepts to life',
      'Уникальные проекты, которые стали реальностью',
    ),
    projectsSubtitle: L(
      'מבחר פרויקטים שמשקף דיוק ואיכות',
      'مجموعة مشاريع بتعكس الدقة والجودة',
      'A selection that reflects precision and quality',
      'Подборка, которая отражает точность и качество',
    ),
    materialsEyebrow: L('חומרים', 'الخامات', 'Materials', 'Материалы'),
    materialsTitle: L(
      'חומרים שנבחרו בקפידה',
      'خامات مختارة بعناية',
      'Carefully selected materials',
      'Тщательно подобранные материалы',
    ),
    materialsSubtitle: L(
      'מגוון אפשרויות לכל סגנון ותקציב',
      'تشكيلة لكل ستايل وميزانية',
      'Options for every style and budget',
      'Варианты под любой стиль и бюджет',
    ),
    testimonialsEyebrow: L('המלצות', 'آراء العملاء', 'Testimonials', 'Отзывы'),
    testimonialsTitle: L(
      'המלצות לקוחות',
      'شهادات نعتز بها',
      'Client Reviews',
      'Клиентские отзывы',
    ),
    testimonialsSubtitle: L(
      'חוויות אמיתיות מהבית ומהעסק',
      'تجارب حقيقية من المنزل والعمل',
      'Real experiences from homes and businesses',
      'Автентичные опыты из дома и бизнеса',
    ),
  },
  about: {
    eyebrow: L('אודות', 'من نحن', 'About', 'О нас'),
    title: L(
      'Nora Group — נגרות ועיצוב פנים מקצועי',
      'Nora Group — نجارة وتصميم داخلي متخصص',
      'Nora Group — carpentry & interiors',
      'Nora Group — столярка и интерьеры',
    ),
    subtitle: L(
      'תכנון · ביצוע · איכות — ממגדל עוז',
      'تخطيط · تنفيذ · جودة — من مجدال عوز',
      'Planning · Execution · Quality — from Migdal Oz',
      'Планирование · Исполнение · Качество — из Мигдаль Оз',
    ),
    image: images.craft1,
    body: L(
      'אנחנו סדנת נגרות ועיצוב פנים שמתמחה בפתרונות מותאמים אישית. כל פרויקט מתחיל בהקשבה ומסתיים בהתקנה מדויקת.',
      'إحنا ورشة نجارة وتصميم داخلي متخصصة بحلول مفصّلة. كل مشروع بيبدأ بالا ستماع وينتهي بتركيب دقيق.',
      'We are a carpentry and interior studio focused on custom solutions. Every project starts with listening and ends with precise installation.',
      'Мы столярная и интерьерная мастерская. Каждый проект начинается с понимания задачи и заканчивается профессиональным монтажом.',
    ),
    valuesTitle: L('הערכים שלנו', 'قيمنا', 'Our values', 'Наши ценности'),
    values: [
      {
        title: L('יושרה', 'صدق', 'Integrity', 'Честность'),
        desc: L(
          'מחיר ברור ועבודה כמו שהבטחנו',
          'سعر واضح وعمل كما وعدنا',
          'Clear pricing and work as promised',
          'Понятная цена и работа как обещали',
        ),
      },
      {
        title: L('מקצועיות', 'احتراف', 'Craft', 'Мастерство'),
        desc: L(
          'ידע, כלים ותשומת לב לפרטים',
          'معرفة، أدوات واهتمام بالتفاصيل',
          'Skill, tools, and care for detail',
          'Навыки, инструменты и внимание к деталям',
        ),
      },
      {
        title: L('אחריות', 'مسؤولية', 'Responsibility', 'Ответственность'),
        desc: L(
          'אנחנו איתכם עד שהמרחב מוכן לשימוש',  
          'نحن معكم حتى يصبح المشروع جاهز للاستخدام',
          'We stay with you until the project is ready for use',
          'Мы рядом, пока проект не готов к использованию',
        ),
      },
    ],
  },
  howWeWork: {
    eyebrow: L('תהליך', 'العملية', 'Process', 'Процесс'),
    title: L('איך אנחנו עובדים', 'كيف نعمل', 'How we work', 'Как мы работаем'),
    subtitle: L(
      'שקיפות בכל שלב',
      'وضوح في كل خطوة',
      'Clarity at every step',
      'Прозрачность на каждом шаге',
    ),
    image: images.office1,
    steps: [
      {
        number: '01',
        title: L('ייעוץ', 'استشارة', 'Consultation', 'Консультация'),
        description: L(
          'מבינים את הצורך והחזון',
          'نفهم الاحتياج والرؤية',
          'We understand the need and the intention',
          'Понимаем задачу и намерение',
        ),
      },
      {
        number: '02',
        title: L('מדידות', 'قياسات', 'Measuring', 'Замеры'),
        description: L(
          'נגיע לאתר ונמדד במדויק',
          'نذهب إلى الموقع ونقيس بدقة',
          'We visit the site and measure precisely',
          'Мы посещаем объект и точно замеряем',
        ),
      },
      {
        number: '03',
        title: L('עיצוב', 'تصميم', 'Design', 'Дизайн'),
        description: L(
          'נערך כיוון עיצוב ותכנית עבודה',
          'نعرض اتجاه التصميم والتخطيط',
          'We present a design direction and plan',
          'Представляем направление дизайна и планировку',
        ),
      },
      {
        number: '04',
        title: L('אישור', 'اعتماد', 'Approval', 'Согласование'),
        description: L(
          'משלימים התאמות ומאשרים יחד',
          'نكمل التعديلات ونعتمدها معا',
          'We complete the adjustments and approve them together',
          'Дорабатываем детали и утверждаем их вместе',
        ),
      },
      {
        number: '05',
        title: L('ייצור', 'تصنيع', 'Manufacturing', 'Производство'),
        description: L(
          'נייצר בסדנה בסטנדרט גבוה',
          'نصنع في الورشة بمعيار عالي',
          'We build in the workshop to a high standard',
          'Изготавливаем в мастерской на высоком уровне',
        ),
      },
      {
        number: '06',
        title: L('התקנה', 'تركيب', 'Installation', 'Монтаж'),
        description: L(
          'נתקן אצלכם במקצועיות',
          'نركب عندكم باحتراف',
          'We install on site professionally',
          'Монтируем на объекте профессионально',
        ),
      },
      {
        number: '07',
        title: L('מסירה', 'تسليم', 'Handover', 'Сдача'),
        description: L(
          'נסיר פרויקט מוכן לשימוש',
          'نسلم مشروع جاهز للاستخدام',
          'We hand over a project ready to use',
          'Передаём проект, готовый к использованию',
        ),
      },
    ],
  },
  contactPage: {
    eyebrow: L('צור קשר', 'تواصل', 'Contact', 'Контакты'),
    title: L('בואו נדבר', 'دعنا نتحدث', "Let's talk", 'Давайте поговорим'),
    subtitle: L(
      'טלפון, וואטסאפ או אימייל',
      'تلفون، واتساب أو بريد إلكتروني',
      'Phone, WhatsApp, or email',
      'Телефон, WhatsApp или электронная почта',
    ),
    image: images.livingRoom2,
  },
  categoryLabels: {
    he: {
      all: 'הכל',
      kitchens: 'מטבחים',
      bedrooms: 'חדרי שינה',
      wardrobes: 'ארונות',
      furniture: 'ריהוט',
      commercial: 'פרויקטים מסחריים',
    },
    ar: {
      all: 'الكل',
      kitchens: 'مطابخ',
      bedrooms: 'غرف نوم',
      wardrobes: 'خزائن الملابس',
      furniture: 'أثاث',
      commercial: 'مشاريع تجارية',
    },
    en: {
      all: 'All',
      kitchens: 'Kitchens',
      bedrooms: 'Bedrooms',
      wardrobes: 'Wardrobes',
      furniture: 'Furniture',
      commercial: 'Commercial projects',
    },
    ru: {
      all: 'Все',
      kitchens: 'Кухни',
      bedrooms: 'Спальни',
      wardrobes: 'Шкафы',
      furniture: 'Мебель',
      commercial: 'Коммерческие проекты',
    },
  },
  services: [
    {
      slug: 'kitchens',
      title: L('מטבחים', 'مطابخ', 'Kitchens', 'Кухни'),
      description: L(
        'מטבחים מותאמים שמשלבים יופי ופונקציה',
        'مطابخ مفصّلة بتجمع الجمال والوظيفة',
        'Custom kitchens that balance beauty and function',
        'Кухни на заказ — красота и функция',
      ),
      image: images.kitchen1,
      features: [
        L('תכנון לפי החלל', 'تخطيط حسب المساحة', 'Planning for your space', 'Планирование для вашего пространства'),
        L('בחירת חומרים', 'اختيار خامات', 'Material selection', 'Выбор материалов по вашим предпочтениям'),
        L('התקנה מלאה', 'تركيب كامل', 'Full installation', 'Полный монтаж на объекте'),
      ],
      visible: true,
    },
    {
      slug: 'bedrooms',
      title: L('חדרי שינה', 'غرف نوم', 'Bedrooms', 'Спальни'),
      description: L(
        'חדרי שינה נוחים ומדויקים',
        'غرف نوم طبيعية ومتقنة',
        'Calm, well-crafted bedrooms',
        'Комфортные и точные спальни',
      ),
      image: images.bedroom1,
      features: [
        L('מיטות וארונות משולבים', 'أسرة مدمجة', 'Beds and built-ins', 'Кровати и встроенные шкафы'),
        L('פתרונות אחסון', 'حلول تخزين', 'Storage solutions', 'Системы хранения вещей'),
        L('גימור חם', 'تشطيب دافئ', 'Warm finishes', 'Теплые отделки'),
      ],
      visible: true,
    },
    {
      slug: 'wardrobes',
      title: L('ארונות', 'خزائن', 'Wardrobes', 'Шкафы'),
      description: L(
        'ארונות חכמים שמנצלים כל סנטימטר',
        'خزائن ملابس ذكية بتستغل كل سانتي',
        'Smart wardrobes that use every inch',
        'Умные шкафы на каждый сантиметр',
      ),
      image: images.wardrobe1,
      features: [
        L('חזיתות בהתאמה', 'واجهات حسب الطلب', 'Custom fronts', 'Фасады на заказ'),
        L('מנגנונים איכותיים', 'آليات ممتازة', 'Quality hardware', 'Качественная фурнитура'),
        L('ארגון פנימי', 'تنظيم داخلي', 'Interior organization', 'Внутренняя организация'),
      ],
      visible: true,
    },
    {
      slug: 'walk-in-closets',
      title: L('חדרי ארונות', 'غرف ملابس', 'Walk-in closets', 'Гардеробные'),
      description: L(
        'חדרי ארונות מאורגנים ומעוצבים',
        'غرف ملابس مرتبة ومصممة تناسسب ذوقك',
        'Organized, designed walk-in closets',
        'Организованные гардеробные',
      ),
      image: images.wardrobe2,
      features: [
        L('תאורה ותצוגה', 'إضاءة وعرض', 'Lighting and display', 'Свет и витрины'),
        L('חלוקה לפי שימוש', 'تقسيم حسب الاستخدام', 'Zones by use', 'Зоны по задачам'),
        L('חוויית יוקרה יומיומית', 'تجربة فخمة يومية', 'Everyday luxury', 'Роскошь на каждый день'),
      ],
      visible: true,
    },
    {
      slug: 'custom-furniture',
      title: L('ריהוט מותאם', 'أثاث مفصّل', 'Custom furniture', 'Мебель на заказ'),
      description: L(
        'רהיטים ייחודיים לפי מידה וסגנון',
        'قطع أثاث فريدة حسب المقاس والستايل',
        'Unique pieces by size and style',
        'Уникальные изделия под размер и стиль',
      ),
      image: images.furniture1,
      features: [
        L('שולחנות ומדפים', 'طاولات ورفوف', 'Tables and shelves', 'Столы и полки'),
        L('יחידות מדיה', 'وحدات تلفزيون', 'Media units', 'ТВ-зоны'),
        L('עבודת יד מדויקת', 'شغل يد دقيق', 'Precise craftsmanship', 'Точная ручная работа'),
      ],
      visible: true,
    },
    {
      slug: 'offices',
      title: L('משרדים', 'مكاتب', 'Offices', 'Офисы'),
      description: L(
        'חללי עבודה פרקטיים ומכובדים',
        'مساحات عمل عملية ومرتبة',
        'Practical, polished workspaces',
        'Практичные и аккуратные офисы',
      ),
      image: images.office1,
      features: [
        L('שולחנות מנהלים', 'طاولات إدارة', 'Executive desks', 'Кабинеты'),
        L('אחסון משרדי', 'تخزين مكتبي', 'Office storage', 'Офисное хранение'),
        L('זהות מותג בחלל', 'هوية بالمكان', 'Brand identity in space', 'Идентичность в пространстве'),
      ],
      visible: true,
    },
    {
      slug: 'commercial',
      title: L('פרויקטים מסחריים', 'مشاريع تجارية', 'Commercial projects', 'Коммерческие проекты'),
      description: L(
        'פתרונות לעסקים, מסעדות וחללים ציבוריים',
        'حلول للمحلات والمطاعم والأماكن العامة',
        'Solutions for shops, restaurants, and public spaces',
        'Решения для магазинов, ресторанов и общественных мест',
      ),
      image: images.commercial1,
      features: [
        L('עמידות לשימוש אינטנסיבי', 'متانة للاستخدام الكثيف', 'Built for heavy use', 'Для интенсивной нагрузки'),
        L('עיצוב בהתאם למותג', 'تصميم حسب الهوية', 'Design aligned to brand', 'Дизайн под бренд'),
        L('לוחות זמנים עסקיים', 'جداول زمنية للشغل', 'Business-aware timelines', 'Сроки с учётом бизнеса'),
      ],
      visible: true,
    },
  ],
  projects: [
    {
      slug: 'modern-wooden-kitchen-01',
      title: L('מטבח עץ מודרני', 'مطبخ خشب عصري', 'Modern wooden kitchen', 'Современная кухня'),
      description: L(
        'מטבח מותאם עם חזיתות עץ ומשטחים נקיים',
        'مطبخ مفصّل بواجهات خشب وأسطح نظيفة',
        'A custom kitchen with wood fronts and clean surfaces',
        'Кухня на заказ с деревянными фасадами',
      ),
      category: 'kitchens',
      images: [images.kitchen1, images.kitchen2, images.kitchen3],
      materials: ['MDF', 'Veneer', 'Natural Wood'],
      visible: true,
    },
    {
      slug: 'luxury-kitchen-island-02',
      title: L('מטבח עם אי', 'مطبخ عصري مع جزيرة', 'Kitchen with island', 'Кухня с островом'),
      description: L(
        'מטבח יוקרתי עם אי מרכזי פונקציונלי',
        'مطبخ فاخر مع جزيرة وسطية عملية',
        'A premium kitchen with a functional island',
        'Премиум-кухня с функциональным островом',
      ),
      category: 'kitchens',
      images: [images.kitchen2, images.kitchen3, images.kitchen1],
      materials: ['HPL', 'Acrylic'],
      visible: true,
    },
    {
      slug: 'serene-bedroom-03',
      title: L('חדר שינה רגוע', 'غرفة نوم هادئة', 'Serene bedroom', 'Спокойная спальня'),
      description: L(
        'חדר שינה בגוונים חמים עם ארונות משולבים',
        'غرفة نوم بألوان دافية مع خزائن مدمجة',
        'A warm-toned bedroom with built-in storage',
        'Спальня в тёплых тонах со встроенными шкафами',
      ),
      category: 'bedrooms',
      images: [images.bedroom1, images.bedroom2],
      materials: ['MDF', 'Melamine'],
      visible: true,
    },
    {
      slug: 'master-bedroom-04',
      title: L('חדר שינה ראשי', 'غرفة نوم رئيسية', 'Master bedroom', 'Главная спальня'),
      description: L(
        'חדר שינה מלא עם תאורה ואחסון חכם',
        'غرفة نوم كاملة مع إضاءة وتخزين ذكي',
        'A complete bedroom with lighting and smart storage',
        'Полная спальня со светом и умным хранением',
      ),
      category: 'bedrooms',
      images: [images.bedroom2, images.bedroom1],
      materials: ['Natural Wood', 'Veneer'],
      visible: true,
    },
    {
      slug: 'walk-in-closet-05',
      title: L('חדר ארונות', 'غرفة ملابس', 'Walk-in closet', 'Гардеробная'),
      description: L(
        'חדר ארונות מאורגן עם תאורה רכה',
        'غرفة ملابس مرتبة مع إضاءة ناعمة',
        'An organized walk-in with soft lighting',
        'Организованная гардеробная с мягким светом',
      ),
      category: 'wardrobes',
      images: [images.wardrobe1, images.wardrobe2, images.wardrobe3],
      materials: ['MDF', 'Acrylic', 'Glass'],
      visible: true,
    },
    {
      slug: 'built-in-wardrobe-06',
      title: L('ארון מובנה', 'خزائن مدمجة', 'Built-in wardrobe', 'Встроенный шкаф'),
      description: L(
        'חדר ארונות מקיר לקיר עם פתרונות אחסון המותאמים לצרכים שלך',
        'غرفة ملابس من جدار لجدار مع حلول تخزين تناسب احتياجاتك',
        'Wall-to-wall walk-in closet with storage solutions tailored to your needs',
        'Гардеробная от стены до стены с решениями для хранения, адаптированными под ваши потребности',
      ),
      category: 'wardrobes',
      images: [images.wardrobe3, images.wardrobe1],
      materials: ['Melamine', 'MDF'],
      visible: true,
    },
    {
      slug: 'custom-furniture-07',
      title: L('ריהוט מותאם', 'أثاث مفصّل', 'Custom furniture', 'Мебель на заказ'),
      description: L(
        'רהיטים ייחודיים בעבודת יד',
        'قطع أثاث فريدة بشغل يد',
        'Unique handcrafted furniture pieces',
        'Уникальная мебель ручной работы',
      ),
      category: 'furniture',
      images: [images.furniture1, images.furniture2, images.livingRoom1],
      materials: ['Natural Wood', 'Metal'],
      visible: true,
    },
    {
      slug: 'commercial-space-08',
      title: L('חלל מסחרי', 'مساحة تجارية', 'Commercial space', 'Коммерческое пространство'),
      description: L(
        'עיצוב פנים מסחרי עם נגרות מותאמת',
        'تصميم داخلي تجاري مع نجارة مفصّلة',
        'Commercial interior with custom millwork',
        'Коммерческий интерьер со столяркой на заказ',
      ),
      category: 'commercial',
      images: [images.commercial1, images.office1, images.livingRoom2],
      materials: ['MDF', 'Veneer', 'Metal'],
      visible: true,
    },
  ],
  materials: [
    {
      slug: 'mdf',
      name: L('MDF', 'MDF', 'MDF', 'MDF'),
      description: L(
        'לוח סיבים חלק לעיצובים מדויקים',
        'لوح ألياف ناعم للتصاميم الدقيقة',
        'Smooth fiberboard for precise designs',
        'Гладкая плита для точных форм',
      ),
      characteristics: L(
        'יציב, קל לעיבוד, משטח אחיד',
        'ثابت، سهل التشكيل، سطح متجانس',
        'Stable, easy to machine, even surface',
        'Стабильная, удобная в обработке',
      ),
      applications: L(
        'ארונות, חזיתות, ריהוט',
        'كبتات، واجهات، أثاث',
        'Cabinets, fronts, furniture',
        'Шкафы, фасады, мебель',
      ),
      finishes: L(
        'פורניר, אקריל, צבע, מלמין',
        'قشرة، أكريليك، دهان، ميلامين',
        'Veneer, acrylic, paint, melamine',
        'Шпон, акрил, краска, меламин',
      ),
      image: images.wood1,
      visible: true,
    },
    {
      slug: 'hpl',
      name: L('HPL', 'HPL', 'HPL', 'HPL'),
      description: L(
        'למינציה עמידה לחום ולחות',
        'رقائق مقاومة للحرارة والرطوبة',
        'Laminate resistant to heat and moisture',
        'Ламинат устойчив к теплу и влаге',
      ),
      characteristics: L(
        'עמיד לשריטות וקל לניקוי',
        'مقاوم للخدش وسهل التنظيف',
        'Scratch-resistant and easy to clean',
        'Стойкий к царапинам, легко моется',
      ),
      applications: L(
        'מטבחים ומשטחי עבודה',
        'مطابخ وأسطح عمل',
        'Kitchens and work surfaces',
        'Кухни и рабочие поверхности',
      ),
      finishes: L('מט, מבריק, עץ', 'مطفي، لامع، خشبي', 'Matte, gloss, wood look', 'Мат, глянец, под дерево'),
      image: images.wood2,
      visible: true,
    },
    {
      slug: 'acrylic',
      name: L('אקריל', 'أكريليك', 'Acrylic', 'Акрил'),
      description: L(
        'משטח מבריק עם עומק יוקרתי',
        'سطح لامع بعمق فاخر',
        'High-gloss surface with luxury depth',
        'Глянцевая поверхность с глубиной',
      ),
      characteristics: L(
        'ברק גבוה וצבעים עשירים',
        'لمعان عالي وألوان غنية',
        'High gloss and rich color',
        'Высокий глянец и насыщенный цвет',
      ),
      applications: L(
        'מטבחים וארונות מודרניים',
        'مطابخ وكبتات عصرية',
        'Modern kitchens and wardrobes',
        'Современные кухни и шкафы',
      ),
      finishes: L('מבריק גבוה', 'لامع عالي', 'High gloss', 'Высокий глянец'),
      image: images.wood3,
      visible: true,
    },
    {
      slug: 'veneer',
      name: L('פורניר', 'قشرة خشب', 'Veneer', 'Шпон'),
      description: L(
        'מראה עץ טבעי עם דפוסים ייחודיים',
        'مظهر خشب طبيعي بأنماط فريدة',
        'Natural wood look with unique grain',
        'Натуральный вид дерева с уникальным рисунком',
      ),
      characteristics: L(
        'חם, אותנטי, אלגנטי',
        'دافئ، أصيل، أنيق',
        'Warm, authentic, elegant',
        'Тёплый, аутентичный, элегантный',
      ),
      applications: L(
        'ריהוט יוקרה ומשרדים',
        'أثاث فاخر ومكاتب',
        'Premium furniture and offices',
        'Премиум-мебель и офисы',
      ),
      finishes: L('מט, שמן, לכה', 'مطفي، زيت، ورنيش', 'Matte, oil, varnish', 'Мат, масло, лак'),
      image: images.wood1,
      visible: true,
    },
    {
      slug: 'melamine',
      name: L('מלמין', 'ميلامين', 'Melamine', 'Меламин'),
      description: L(
        'פתרון עמיד ומשתלם',
        'حل متين واقتصادي',
        'A durable, cost-effective option',
        'Прочный и выгодный вариант',
      ),
      characteristics: L(
        'קל לתחזוקה ומגוון עיצובים',
        'سهل الصيانة وتشكيلات واسعة',
        'Low maintenance with many looks',
        'Простой уход и много декоров',
      ),
      applications: L(
        'ארונות וחללים מסחריים',
        'كبتات ومساحات تجارية',
        'Wardrobes and commercial spaces',
        'Шкафы и коммерческие пространства',
      ),
      finishes: L('מט, עץ, צבעוני', 'مطفي، خشبي، ملون', 'Matte, wood, solid color', 'Мат, дерево, цвет'),
      image: images.wood2,
      visible: true,
    },
    {
      slug: 'natural-wood',
      name: L('עץ טבעי', 'خشب طبيعي', 'Natural wood', 'Натуральное дерево'),
      description: L(
        'עץ מלא עם אופי וחום',
        'خشب صلب بطابع دافئ',
        'Solid wood with character and warmth',
        'Массив с характером и теплом',
      ),
      characteristics: L(
        'עמיד וייחודי בכל לוח',
        'متين وفريد بكل لوح',
        'Durable; every board is unique',
        'Прочный; каждая доска уникальна',
      ),
      applications: L(
        'ריהוט ואזורי מוקד',
        'أثاث ومناطق بارزة',
        'Furniture and feature areas',
        'Мебель и акцентные зоны',
      ),
      finishes: L('שמן, שעווה, לכה', 'زيت، شمع، ورنيش', 'Oil, wax, varnish', 'Масло, воск, лак'),
      image: images.wood3,
      visible: true,
    },
    {
      slug: 'glass',
      name: L('זכוכית', 'زجاج', 'Glass', 'Стекло'),
      description: L(
        'שקיפות וקלילות לחלל',
        'شفافية وخفة للمساحة',
        'Transparency and lightness in the space',
        'Прозрачность и лёгкость в пространстве',
      ),
      characteristics: L(
        'מודרני ומרחיב ויזואלית',
        'عصري وبوسّع بصرياً',
        'Modern and visually expansive',
        'Современно и визуально расширяет',
      ),
      applications: L(
        'חזיתות מדפים ותצוגה',
        'واجهات رفوف وعرض',
        'Shelf fronts and display',
        'Фасады полок и витрины',
      ),
      finishes: L('שקוף, מט, צבעוני', 'شفاف، مطفي، ملون', 'Clear, frosted, tinted', 'Прозрачное, матовое, цветное'),
      image: images.wood1,
      visible: true,
    },
    {
      slug: 'metal',
      name: L('מתכת', 'معدن', 'Metal', 'Металл'),
      description: L(
        'פרטי מתכת לעמידות וסגנון',
        'تفاصيل معدن للمتانة والأناقة',
        'Metal details for strength and style',
        'Металлические детали для прочности и стиля',
      ),
      characteristics: L(
        'חזק ומגוון בגימורים',
        'قوي ومتعدد التشطيبات',
        'Strong with many finishes',
        'Прочный с разными покрытиями',
      ),
      applications: L(
        'ידיות, רגליים ומסגרות',
        'مقابض، أرجل وإطارات',
        'Handles, legs, and frames',
        'Ручки, ножки и каркасы',
      ),
      finishes: L('שחור, זהב, מוברש', 'أسود، ذهبي، مصقول', 'Black, gold, brushed', 'Чёрный, золото, браш'),
      image: images.wood2,
      visible: true,
    },
  ],
  testimonials: [
    {
      id: '1',
      name: 'לקוח/ה א׳',
      rating: 5,
      review: L(
        'חוויה יוצאת דופן בכל פרט; ביצוע מדויק, איכות בלתי מתפשרת ומטבח שתוכנן לשלב בין יוקרה לפונקציונליות בכל יום.',
        'تجربة استثنائية بكل تفاصيلها؛ دقة في التنفيذ، جودة واضحة، ومطبخ صُمم ليجمع بين الفخامة والعملية في كل يوم..',
        'An exceptional experience in every detail — impeccable craftsmanship, uncompromising quality, and a kitchen designed to unite luxury with everyday functionality.',
        'Исключительный опыт в каждой детали — безупречное исполнение, бескомпромиссное качество и кухня, созданная для гармоничного сочетания роскоши и функциональности.',
      ),
      project: L('מטבח מותאם', 'مطبخ مفصّل', 'Custom kitchen', 'Кухня на заказ'),
      visible: true,
    },
    {
      id: '2',
      name: 'לקוח/ה ב׳',
      rating: 5,
      review: L(
        'חדר הארונות שינה לנו את הסדר בבית.',
        'غرفة الملابس غيّرت النظام عندنا بالبيت.',
        'The walk-in closet changed how we organize at home.',
        'Гардеробная изменила порядок дома.',
      ),
      project: L('חדר ארונות', 'غرفة ملابس', 'Walk-in closet', 'Гардеробная'),
      visible: true,
    },
    {
      id: '3',
      name: 'לקוח/ה ג׳',
      rating: 5,
      review: L(
        'תשומת לב לפרטים ולוחות זמנים שעבדו.',
        'اهتمام بالتفاصيل ومواعيد دقيقة.',
        'Attention to detail and timelines that held.',
        'Внимание к деталям и сроки, которые держали.',
      ),
      project: L('חדר שינה', 'غرفة نوم', 'Bedroom', 'Спальня'),
      visible: true,
    },
  ],
  blogPosts: [
    {
      slug: 'choosing-kitchen-materials',
      title: L(
        'איך בוחרים חומרים למטבח',
        'كيف تختاروا خامات المطبخ',
        'How to choose kitchen materials',
        'Как выбрать материалы для кухни',
      ),
      excerpt: L(
        'מדריך קצר ל־MDF, HPL ועץ טבעי',
        'دليل مختصر لـ MDF و HPL والخشب الطبيعي',
        'A short guide to MDF, HPL, and natural wood',
        'Краткий гид по MDF, HPL и массиву',
      ),
      content: L(
        'בחירת החומרים משפיעה על עמידות, תחזוקה ומראה. נשמח לייעץ לפי השימוש שלכם.',
        'اختيار الخامات بيأثر على المتانة والصيانة والمظهر. منسرّ نستشيركم حسب استخدامكم.',
        'Material choice affects durability, care, and look. We are happy to advise for your use case.',
        'Выбор материалов влияет на прочность, уход и вид. С радостью подскажем под ваши задачи.',
      ),
      category: 'kitchens',
      author: 'Nora Group',
      date: '2025-01-15',
      image: images.kitchen1,
      visible: true,
    },
    {
      slug: 'wardrobe-trends',
      title: L(
        'מגמות בארונות ובחדרי ארונות',
        'اتجاهات الخزائن وغرف الملابس',
        'Wardrobe and walk-in trends',
        'Тренды шкафов и гардеробных',
      ),
      excerpt: L(
        'אחסון חכם וחזיתות נקיות',
        'تخزين ذكي وواجهات نظيفة',
        'Smart storage and clean fronts',
        'Умное хранение и чистые фасады',
      ),
      content: L(
        'המגמות מתמקדות בניצול שטח, תאורה ותנועה נוחה.',
        'الاتجاهات بتركّز على استغلال المساحة والإضاءة والحركة المريحة.',
        'Trends focus on space use, lighting, and easy movement.',
        'Тренды — использование пространства, свет и удобное движение.',
      ),
      category: 'trends',
      author: 'Nora Group',
      date: '2025-02-20',
      image: images.wardrobe1,
      visible: true,
    },
    {
      slug: 'wood-care',
      title: L(
        'איך שומרים על ריהוט עץ',
        'كيف تحافظوا على أثاث الخشب',
        'How to care for wood furniture',
        'Как ухаживать за деревянной мебелью',
      ),
      excerpt: L(
        'טיפים פשוטים לאורך חיים ארוך',
        'نصائح بسيطة لعمر أطول',
        'Simple tips for longer life',
        'Простые советы для долгой службы',
      ),
      content: L(
        'ניקוי עדין, הרחקה מלחות עודפת ובדיקת גימור מדי פעם.',
        'تنظيف لطيف، ابتعاد عن الرطوبة الزيادة وفحص التشطيب من وقت للتاني .',
        'Gentle cleaning, avoiding excess moisture, and checking finishes occasionally usually suffice.',
        'Мягкая очистка, защита от лишней влаги и периодический осмотр покрытия.',
      ),
      category: 'care',
      author: 'Nora Group',
      date: '2025-03-10',
      image: images.furniture1,
      visible: true,
    },
  ],
  faq: [
    {
      id: '1',
      category: 'general',
      question: L('כמה זמן לוקח פרויקט?', 'كم يأخدوقتالمشروع؟', 'How long does a project take?', 'Сколько длится проект?'),
      answer: L(
        'תלוי בהיקף. אחרי שיחה ראשונה נותנים לוח זמנים ברור.',
        'حسب حجم الشغل. بعد أول محادثة بنعطي جدول زمني واضح.',
        'It depends on scope. After the first call we give a clear timeline.',
        'Зависит от объёма. После первого разговора даём понятный график.',
      ),
      visible: true,
    },
    {
      id: '2',
      category: 'general',
      question: L('יש אחריות?', 'في كفالة؟', 'Is there a warranty?', 'Есть гарантия?'),
      answer: L(
        'כן — נפרט את תנאי האחריות בשיחה ובמסמך ההזמנה.',
        'نعم — منفصّل شروط الكفالة بالمحادثة وبمستند الطلب.',
        'Yes — we detail warranty terms on the call and in the order document.',
        'Да — условия гарантии уточняем в разговоре и в документе заказа.',
      ),
      visible: true,
    },
    {
      id: '3',
      category: 'services',
      question: L('מה אתם מייצרים?', 'شو بتصنّعوا؟', 'What do you make?', 'Что вы делаете?'),
      answer: L(
        'מטבחים, חדרי שינה, ארונות, חדרי ארונות, ריהוט מותאם, משרדים ופרויקטים מסחריים.',
        'مطابخ، غرف نوم، خزائن ملابس، غرف ملابس، أثاث مفصّل، مكاتب ومشاريع تجارية.',
        'Kitchens, bedrooms, wardrobes, walk-ins, custom furniture, offices, and commercial work.',
        'Кухни, спальни, шкафы, гардеробные, мебель на заказ, офисы и коммерция.',
      ),
      visible: true,
    },
    {
      id: '4',
      category: 'services',
      question: L('יש עיצוב תלת־ממד?', 'في تصميم ثلاثي الأبعاد؟', 'Do you offer 3D design?', 'Есть 3D-дизайн?'),
      answer: L(
        'כן, כדי שתראו את הכיוון לפני הייצור.',
        'نعم، عشان تشوفوا الاتجاه قبل التصنيع.',
        'Yes, so you can see the direction before manufacturing.',
        'Да, чтобы вы увидели направление до производства.',
      ),
      visible: true,
    },
    {
      id: '5',
      category: 'materials',
      question: L('אילו חומרים יש?', 'أي خامات متوفرة؟', 'What materials are available?', 'Какие материалы доступны?'),
      answer: L(
        'בין היתר MDF, HPL, אקריל, פורניר, מלמין, עץ טבעי, זכוכית ומתכת.',
        'من بينها MDF و HPL وأكريليك وقشرة وميلامين وخشب طبيعي وزجاج ومعدن.',
        'Including MDF, HPL, acrylic, veneer, melamine, natural wood, glass, and metal.',
        'В том числе MDF, HPL, акрил, шпон, меламин, массив, стекло и металл.',
      ),
      visible: true,
    },
    {
      id: '6',
      category: 'pricing',
      question: L('איך נקבע המחיר?', 'كيف بيتحدد السعر؟', 'How is pricing set?', 'Как формируется цена?'),
      answer: L(
        'לפי סוג הפרויקט, חומרים, מידות ועיצוב — אחרי ייעוץ.',
        'حسب نوع المشروع والخامات والمقاسات والتصميم — بعد الاستشارة.',
        'By project type, materials, dimensions, and design — after consultation.',
        'По типу проекта, материалам, размерам и дизайну — после консультации.',
      ),
      visible: true,
    },
    {
      id: '7',
      category: 'contact',
      question: L('איך יוצרים קשר?', 'كيف منقدر نتواصل؟', 'How do we reach you?', 'Как с вами связаться?'),
      answer: L(
        'בטלפון או בוואטסאפ.',
        ' واتساب .',
        'By phone or WhatsApp.',
        'По телефону или WhatsApp.',
      ),
      visible: true,
    },
    {
      id: '8',
      category: 'installation',
      question: L('אתם מתקינים?', 'بتركّبوا؟', 'Do you install?', 'Вы монтируете?'),
      answer: L(
        'כן, הצוות שלנו מתקין באתר.',
        'نعم، فريقنا بركّب بالموقع.',
        'Yes, our team installs on site.',
        'Да, наша команда монтирует на объекте.',
      ),
      visible: true,
    },
  ],
  ui: {
    he: {
      footerCta: 'בואו ניצור יחד את הפרויקט שלכם',
      footerTagline: 'נגרות ועיצוב פנים — תכנון, ביצוע ואיכות',
      servicesTitle: 'שירותים',
      navTitle: 'ניווט',
      contactTitle: 'יצירת קשר',
      languagesTitle: 'שפות',
      madeBy: 'נבנה על ידי',
      notFoundTitle: 'העמוד לא נמצא',
      notFoundBody: 'ייתכן שהקישור שגוי או שהעמוד הוסר.',
      relatedProjects: 'פרויקטים קשורים',
      demoNotice: '',
    },
    ar: {
      footerCta: 'خلينا نصنع مشروعكم سوا',
      footerTagline: 'نجارة وتصميم داخلي — تخطيط، تنفيذ وجودة',
      servicesTitle: 'خدمات',
      navTitle: 'تصفح',
      contactTitle: 'تواصل',
      languagesTitle: 'اللغات',
      madeBy: 'من تنفيذ',
      notFoundTitle: 'الصفحة غير موجودة',
      notFoundBody: 'ممكن الرابط غلط أو الصفحة انشالت.',
      relatedProjects: 'مشاريع ذات صلة',
      demoNotice: '',
    },
    en: {
      footerCta: "Let's build your project together",
      footerTagline: 'Carpentry & interiors — planning, execution, quality',
      servicesTitle: 'Services',
      navTitle: 'Explore',
      contactTitle: 'Contact',
      languagesTitle: 'Languages',
      madeBy: 'Made by',
      notFoundTitle: 'Page not found',
      notFoundBody: 'The link may be wrong or the page was removed.',
      relatedProjects: 'Related projects',
      demoNotice: '',
    },
    ru: {
      footerCta: 'Давайте создадим ваш проект вместе',
      footerTagline: 'Столярка и интерьеры — планирование, исполнение, качество',
      servicesTitle: 'Услуги',
      navTitle: 'Навигация',
      contactTitle: 'Контакты',
      languagesTitle: 'Языки',
      madeBy: 'Сделано',
      notFoundTitle: 'Страница не найдена',
      notFoundBody: 'Возможно, ссылка неверна или страница удалена.',
      relatedProjects: 'Похожие проекты',
      demoNotice: '',
    },
  },
};
